apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30095
    protocol: TCP
  selector:
    app: {{ .Values.appName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.app }}
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: {{ .Values.service.app }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.app }}
    spec:
      containers:
      - name: mysql
        image: "mysql:5.7"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "{{ .Values.mysql.RootPassword }}"
        - name: MYSQL_DATABASE
          value: "{{ .Values.mysql.Prestashop }}"
        - name: MYSQL_USER
          value: "{{ .Values.mysql.Prestashop }}"
        - name: MYSQL_PASSWORD
          value: "{{ .Values.mysql.mysqlPassword }}"